title: Hai Nguyen-Hoang Pham (Henrik) 范阮皇海
description: "\"When you come out of the storm, you won't be the same person who walked in.\" - Haruki Murakami"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

redirect_to: /eu.md
